---
- hosts: redhat2
  gather_facts: false
  user: yuan
  become: yes

  vars:
    panganay: "Theodore Yuan Bourne"  
    bunso: "Yuri Alexei"  

  tasks:
    - name: Print the name of my First Son
      debug:
        msg: "The name of my first Son is {{ panganay }}"

    - name: Print the name of my Second Son
      debug:
        msg: "The name of my second Son is {{ bunso }}"

# Try this by running below command:
# ansible-playbook Vars_Inside_A_File.yaml
