---
- hosts: redhat2
  user: yuan
  become_user: root
  become_method: su
  ignore_errors: yes
  
  tasks:
    - block:
        - name: Download the Primary Inventory File Template
          get_url:
            url: http://192.168.56.106/InventoryReport.rpt
            dest: /tmp/InventoryReport.rpt
        - name: Copy the Inventory File Template to the target server/s
          template:
            src: InventoryReport1.template
            dest: /tmp/InventoryReport.rpt
      rescue:
        - name: Copy the Alternative Inventory File Template
          template:
            src: InventoryReport2.template
            dest: /tmp/InventoryReport.rpt
