
# **************************************************************
# Author : matawala
#
# Prerequisite/s
# Create a InventoryReport.rpt file in the webserver
# Create templates InventoryReport[1&2].template locally
# **************************************************************

---
- hosts: redhat2
  user: yuan
  become_user: root
  become_method: su
  #ignore_errors: yes
  
  tasks:
    - block:
        - name: Download the Primary Inventory File Template
          get_url:
            url: http://192.168.56.106:88/InventoryReport.rpt
            dest: /root/InventoryReport.rpt
        - name: Copy the Inventory Report to the target server/s
          template:
            src: InventoryReport1.template
            dest: /root/InventoryReport.rpt
      rescue:
        - name: Copy the Alternative Inventory File Template
          template:
            src: InventoryReport2.template
            dest: /root/InventoryReport.rpt
